import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import base64
from PIL import Image

def create_pdf_report(prediction_data, user_data, doctor_notes):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 18)
    c.drawString(0.5*inch, height - 1*inch, "OCT AI DIAGNOSIS REPORT")
    
    c.setLineWidth(1)
    c.line(0.5*inch, height - 1.2*inch, width - 0.5*inch, height - 1.2*inch)

    # Details
    c.setFont("Helvetica", 10)
    c.drawString(0.5*inch, height - 1.5*inch, f"Patient ID: {user_data.get('id', 'N/A')}")
    c.drawString(0.5*inch, height - 1.7*inch, f"Report Date: {prediction_data['created_at'].strftime('%Y-%m-%d %H:%M:%S')} UTC")
    c.drawString(0.5*inch, height - 1.9*inch, "Analysis By: OCT AI Diagnosis v1.0")
    
    # Diagnosis Result
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.5*inch, height - 2.4*inch, "DIAGNOSIS RESULT")
    c.line(0.5*inch, height - 2.5*inch, 2.5*inch, height - 2.5*inch)
    
    c.setFont("Helvetica", 11)
    c.drawString(0.5*inch, height - 2.8*inch, f"Predicted Condition: {prediction_data['predicted_class']}")
    c.drawString(0.5*inch, height - 3.0*inch, f"Confidence Score: {prediction_data['confidence']:.1f}%")
    
    # Probabilities
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.5*inch, height - 3.5*inch, "CLASS PROBABILITIES")
    c.line(0.5*inch, height - 3.6*inch, 2.5*inch, height - 3.6*inch)
    
    y = height - 3.9*inch
    for cls, prob in prediction_data['probabilities'].items():
        c.setFont("Helvetica", 10)
        c.drawString(0.5*inch, y, f"{cls}: {prob*100:.1f}%")
        # Draw a simple bar
        c.setFillColor(colors.lightgrey)
        c.rect(2*inch, y-2, 2*inch, 10, fill=1, stroke=0)
        c.setFillColor(colors.blue)
        c.rect(2*inch, y-2, 2*inch * prob, 10, fill=1, stroke=0)
        c.setFillColor(colors.black)
        y -= 0.2*inch
        
    # Images (decode base64)
    try:
        orig_img_data = base64.b64decode(prediction_data['original_image'])
        cam_img_data = base64.b64decode(prediction_data['gradcam_image'])
        
        from reportlab.lib.utils import ImageReader
        orig_img = ImageReader(io.BytesIO(orig_img_data))
        cam_img = ImageReader(io.BytesIO(cam_img_data))
        
        c.drawImage(orig_img, 0.5*inch, y - 2.5*inch, width=2.5*inch, height=2.5*inch)
        c.drawImage(cam_img, 3.5*inch, y - 2.5*inch, width=2.5*inch, height=2.5*inch)
        
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(0.5*inch, y - 2.7*inch, "Original Scan")
        c.drawString(3.5*inch, y - 2.7*inch, "Grad-CAM Highlight")
        y -= 3.0*inch
    except Exception as e:
        c.drawString(0.5*inch, y - 0.5*inch, "(Error loading images)")
        y -= 1.0*inch

    # Doctor Notes
    c.setFont("Helvetica-Bold", 12)
    c.drawString(0.5*inch, y, "DOCTOR NOTES")
    c.line(0.5*inch, y - 0.1*inch, 2.5*inch, y - 0.1*inch)
    
    c.setFont("Helvetica", 10)
    y -= 0.4*inch
    if doctor_notes:
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph
        style = getSampleStyleSheet()['Normal']
        p = Paragraph(doctor_notes, style)
        p.wrapOn(c, width - 1*inch, 2*inch)
        p.drawOn(c, 0.5*inch, y - p.height)
        y -= p.height + 0.2*inch
    else:
        c.drawString(0.5*inch, y, "No notes provided.")
        y -= 0.3*inch

    # Footer / Disclaimer
    c.line(0.5*inch, 1.5*inch, width - 0.5*inch, 1.5*inch)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(0.5*inch, 1.3*inch, "DISCLAIMER:")
    c.setFont("Helvetica", 8)
    c.drawString(0.5*inch, 1.15*inch, "This report is generated by an AI model and is intended for research and educational purposes only.")
    c.drawString(0.5*inch, 1.0*inch, "It does not constitute a medical diagnosis. Always consult a qualified ophthalmologist.")

    c.save()
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes
